### ISSUE TITLE
Wait() never unblocks when no goroutine is running

### ISSUE THREAD

**Issue by tchap** [go-tomb/tomb#14]
Hi,

I am using `tomb` to monitor rather short-lived goroutines. It is possible that no goroutine is running when I do `Kill(nil)` and `Wait()`, or even no goroutines has ever been started. I find it strange and not very intuitive that in this case `Wait()` blocks forever. Wouldn't it make more sense to close the dead channel immediately when no registered goroutine is running?

**Comment by niemeyer** [comment]
It would be stranger to allow Wait to be called and to unblock it immediately because the logic did not yet reach the point of starting to goroutine. If the background activity won't be started, return an error rather than allowing concurrent code to manipulate the tomb that will never have background activity related to it.
