### ISSUE TITLE
Panics can happen if the first callback finishes very quickly

### ISSUE THREAD

**Issue by ralfthewise** [go-tomb/tomb#16]
Consider the somewhat contrived example:
```
        nothing := func() error { return nil }
        tb := &tomb.Tomb{}
        tb.Go(nothing)
        time.Sleep(100 * time.Millisecond)
        tb.Go(nothing)
        tb.Wait()
```

If you run this, it will panic.  You could certainly make the argument that there's no need for using a goroutine if your callback can return immediately, but imagine the case where the callback does some validation and error checking and fails quickly if problems are found but otherwise does some longer running operation.

**Comment by niemeyer** [comment]
That's actually a pretty simple example, and the reason it panics is because it's breaking the contract offered by the tomb package. Per the [documentation](https://gopkg.in/tomb.v2#Tomb.Go):
> Calling the Go method after all tracked goroutines return causes a runtime panic. For that reason, calling the Go method a second time out of a tracked goroutine is unsafe.

**Comment by niemeyer** [comment]
To be clear, and sorry for not saying that upfront, one trivial way to fix that is to simply spawn your secondary or parallel goroutines from within the goroutine that is spawned when calling tomb.Go.

As for the rationale, the tomb starts up in a state in which it will block any calls to Wait until the goroutine runs. This ensures that are no races between calling something that will do tomb.Go and something that will do tomb.Wait or similar. But then, once you do run tomb.Go, this may return, which means that blocked tomb.Wait may be unblocked once it returns.

So, the panic is actually a good measure that warns you "Hey! You have a bad race in your code!", and that's why it can't simply be avoided unless the whole semantics of the package change.
